### ISSUE TITLE
Sagemaker module can't be imported

### ISSUE THREAD

**Issue by mludvig** [qtangs/sagemaker-notebook-container#3]
Hi, in the latest *qtangs/sagemaker-notebook:python3-tensorflow-p36* (a5c579747df1) docker image I'm unable to do `import sagemaker`, it fails with incompatibility between `sagemaker` and `python-dateutil`. 

The installed `python-dateutil` is version `2.8.1` but `sagemaker` requires `<2.8.1`. I had to downgrade it in the shell with `conda install -n python3 'python-dateutil<2.8.1'`, now `import sagemaker` works.

Not sure if we need sagemaker upgraded or dateutil downgraded but as it is it doesn't work.

**Comment by qtangs** [comment]
Thanks for reporting the bug.

The root cause is related to this line in [Dockerfile](https://github.com/qtangs/sagemaker-notebook-container/blob/master/envs/docker/Dockerfile.python3#L17):
`$HOME/envs/create_env_file.sh python3`

This line creates the conda env file by selecting a subset of all libraries from the original SageMaker environments (so as to reduce Docker image size). The subset is defined by [`include_libraries.txt`](https://github.com/qtangs/sagemaker-notebook-container/blob/master/envs/include_libraries.txt).
Since I put only the high-level libraries (like `sagemaker`, `pandas`, `scikit-learn`) in there, latest versions of dependent libraries are taken during `conda env create`, which results in `python-dateutil` having version `2.8.1`.

I have [corrected this](https://github.com/qtangs/sagemaker-notebook-container/commit/24518c17fc37939c00c92fdb9a73125f5b52f414) and now include all dependent libraries in `include_libraries.txt`. Now `python-dateutil` in `python3` environment should have version `2.7.3`, just like to original environment in this code:
https://github.com/qtangs/sagemaker-notebook-container/blob/master/envs/env_exports/python3.yml#L233

Please try the new image (currently building) and let me know if you can run `import sagemaker` successfully without any changes.
